version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - errorlint
    - exhaustruct
    - funlen
    - ireturn
    - mnd
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - wsl
    - godox
    - gosec
    - noinlineerr
    - unused
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
        - experimental
        - opinionated
    goheader:
      template: |-
        Copyright (c) Ultraviolet
        SPDX-License-Identifier: Apache-2.0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 100
  max-same-issues: 100
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
