http:
  middlewares:
    retry-middleware:
      retry:
        attempts: 4
        initialInterval: 100ms
    headers-middleware:
      headers:
        frameDeny: true
        browserXssFilter: true
    strip-ollama-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/ollama"
    strip-auth-health-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/auth"
    strip-invitations-health-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/invitations"
    strip-users-health-prefix-middleware:
      stripPrefix:
        prefixes:
          - "/users"

  services:
    users:
      loadBalancer:
        servers:
          - url: http://users:9002
        healthCheck:
          scheme: http
          path: /health
          interval: 10s
          timeout: 10s

    auth:
      loadBalancer:
        servers:
          - url: http://auth:8189
        healthCheck:
          scheme: http
          path: /health
          interval: 10s
          timeout: 10s

    invitations:
      loadBalancer:
        servers:
          - url: http://invitations:9020
        healthCheck:
          scheme: http
          path: /health
          interval: 10s
          timeout: 10s

    ollama:
      loadBalancer:
        servers:
          - url: http://ollama:11434
        healthCheck:
          scheme: http
          path: /
          interval: 10s
          timeout: 10s

  # Listed in ascending order of priority

  routers:
    health:
      rule: "Path(`/health`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 10

    users-health:
      rule: "Path(`/users/health`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - strip-users-health-prefix-middleware
        - retry-middleware
        - headers-middleware
      priority: 10

    auth-health:
      rule: "Path(`/auth/health`)"
      entryPoints:
        - websecure
      service: auth
      middlewares:
        - strip-auth-health-prefix-middleware
        - retry-middleware
        - headers-middleware
      priority: 10

    invitations-health:
      rule: "Path(`/invitations/health`)"
      entryPoints:
        - websecure
      service: invitations
      middlewares:
        - strip-invitations-health-prefix-middleware
        - retry-middleware
        - headers-middleware
      priority: 10

    ollama:
      rule: "PathPrefix(`/ollama`)"
      entryPoints:
        - websecure
      service: ollama
      middlewares:
        - strip-ollama-prefix-middleware
        - retry-middleware
        - headers-middleware
      priority: 9

    users-groups:
      rule: "Path(`/groups/{group_id}/users`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    users-channels:
      rule: "Path(`/channels/{channel_id}/users`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    users:
      rule: "PathPrefix(`/users`) || PathPrefix(`/password`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 7

    groups-channels:
      rule: "Path(`/channels/{member_id}/groups`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    groups-users:
      rule: "Path(`/users/{member_id}/groups`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    groups:
      rule: "PathPrefix(`/groups`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 7

    domains:
      rule: "Path(`/domains/{domain_id}/users`)"
      entryPoints:
        - websecure
      service: users
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    auth-domains:
      rule: "Path(`/users/{member_id}/domains`)"
      entryPoints:
        - websecure
      service: auth
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 8

    auth:
      rule: "PathPrefix(`/policies`) || PathPrefix(`/keys`) || PathPrefix(`/domains`)"
      entryPoints:
        - websecure
      service: auth
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 7

    invitations:
      rule: "PathPrefix(`/invitations`)"
      entryPoints:
        - websecure
      service: invitations
      middlewares:
        - retry-middleware
        - headers-middleware
      priority: 7
