# Copyright (c) Ultraviolet
# SPDX-License-Identifier: Apache-2.0

name: Build and Publish Cube AI UI Docker Image

on:
  schedule:
    - cron: '0 8 * * 6'
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  MG_DOCKER_IMAGE_NAME_PREFIX: ghcr.io/ultravioletrs/cube/ui

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Clone UI repository
        env:
          GITHUBPAT: ${{ secrets.GITHUBPAT }}
        run: |
          git config --global url."https://${{ secrets.GITHUBPAT }}@github.com/".insteadOf "https://github.com/"
          git clone ${{ env.REPO_URL }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBPAT }}

      - name: Extract Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.MG_DOCKER_IMAGE_NAME_PREFIX }}/ui-cube-ai

      - name: Build Cube AI UI Docker Image
        run: |
          cd magistrala-ui-new
          GITHUB_TOKEN="${{ secrets.GITHUBPAT }}" make dockers_cube_ai
        
        continue-on-error: false

      - name: Push Cube AI UI Docker Image
        run: |
          docker push ${{ env.MG_DOCKER_IMAGE_NAME_PREFIX }}/ui-cube-ai
        continue-on-error: false
